server.port=5001
server.bufferSize=65535
server.mode=slave
server.slaves=
admin.default.password=123

db.url=jdbc:postgresql://localhost:5432/postgres
db.user=postgres
db.password=12345
db.schema=public